export const TRACKER_ID = {
	LOAD:'页面加载',
	RULR:'活动规则',
	RECORD:'中奖纪录',
	SLIDING:"滑动箭头",
	GO_NEXT:	'浮层-樱花来袭',
	
	OPEN_BAG:	'拆福袋',
	POPUP_SHOW_TASK:'任务弹框加载',	
	POPUP_GO_TASK:	'任务列表-任务去完成',
	POPUP_GO_SHOP:	'任务列表-浏览店铺去完成',

	POPUP_SHOW_BIND:'入会页加载',
	POPUP_SHOW_FOLLOW:'关注页加载',
	POPUP_GO_FOLLOW:	'弹框-去关注',
	POPUP_GO_BIND:	'弹框-去入会',
	MEMBER_SEND_SMS:'入会发送短信',
	MEMBER_INFO:'入会任务曝光',
	FOLLOW_INFO:'关注任务曝光',
	MEMBER_BIND_SUCCESS:'授权入会成功',
    MEMBER_BIND_FAIL:'授权入会失败',
	MEMBER_BIND_ERROR:'授权入会异常',
	FOLLOW_ADD_SUCCESS:'关注成功',
    FOLLOW_ADD_FAIL:'关注失败',
	FOLLOW_ADD_ERROR:'关注异常',

	UPDATE_FOLLOW_TASK:'关注任务完成',
	UPDATE_MEMBER_TASK:'入会任务完成',
	UPDATE_SHOP_TASK:'到店任务完成',
	UPDATE_BAG:'福袋开启',

	POPUP_SHOW_DRAW_RESULT:'抽奖结果弹框',
	POPUP_SHOW_NO_DRAW:'没有抽奖次数了弹框',
	POPUP_GO_SHOP:'弹窗-进店逛逛',
	POPUP_GO_BANNER:'弹窗-打开Banner',
	POPUP_MORE_DRAW:'弹框-更多抽奖次数',

	POPUP_CLOSE:'弹框关闭',

	PUSH_WINDOW:'页面跳转',
	GO_BACK_TOP:'回到顶部',
	DRAW_MORE:	'更多福袋',
	MY_DRAW:	'模块名-我的奖品',
	FLASH_SALE:"秒杀-商品名称",
	MUST_BUY:"必买-商品名称",
	BAND_NAME:"品牌-品牌名称",
	BAND_GOODS:"品牌-商品名称",
}